/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Chapter } from "../types";

export const chaptersData: Chapter[] = [
  {
    id: "ch1",
    number: "1",
    title: "Introduction & Research Framework",
    description: "Foundational aspects of mutual funds, literature reviews, objectives, methodology, and limitations of the study.",
    sections: [
      {
        id: "ch1_1",
        title: "1.1 Introduction",
        page: 11,
        content: [
          "A mutual fund is a type of trust that unites the savings of several investors who have similar financial objectives. The funds thus raised are then invested in assets such as shares, debentures, and other capital market instruments. According to the number of units they own, the income generated by these investments and the capital gains obtained are distributed among the unit holders. Therefore, a mutual fund is the best type of investment for the average person since it provides the chance to invest in a variety of professionally managed assets at a reasonable price.",
          "The Securities and Exchange Board of India (SEBI) has registered a body corporate known as a mutual fund that pools money from individual and corporate investors, invests it on behalf of the investors/unit holders in equity shares, government securities, bonds, call money markets, etc., and distributes the profits. In other words, a mutual fund enables investors to hold a position in a portfolio of assets without actually doing so.",
          "By issuing units to investors and investing money in securities in accordance with the objectives stated in the offer document, mutual funds are a vehicle for pooling resources. The risk is decreased since investments in securities are diversified over a diverse range of industries and sectors. Because not all stocks will move in the same way at the same time in the same proportion, diversification lowers risk. Unit holders are individuals who invest in mutual funds.",
          "Profits and losses are divided among investors according to their respective investments. The mutual funds typically release a number of schemes with various investment objectives that are introduced periodically. Before receiving contributions from the general public, a mutual fund must register with the Securities Exchange Board of India (SEBI), which oversees the securities markets.",
          "When the Unit Trust of India (UTI) was established by the Indian government in 1963, the mutual fund sector in that country officially got underway. With assets of more than Rs. 76,547 crores as of March 31, 2000, UTI developed into a prominent participant in the market. The Unit Trust of India Act, 1963 governed UTI. Mutual funds were subsequently opened to public sector banks and insurance firms in 1987, and then to the private sector in 1993."
        ]
      },
      {
        id: "ch1_2",
        title: "1.2 Review of Literature",
        page: 13,
        content: [
          "Y. Maheshwari (2020): Noted that the Indian capital market offers an assortment of venture options. Mutual funds ensure maximum return and minimal risk to investors. The asset management companies (AMCs) play a dominant role in promoting investment practices. There are currently 44 AMCs in India, and close monitoring of performance metrics (Beta, Standard Deviation, Treynor's measure, Sharpe ratio) is essential for future investment choices.",
          "Deepak Adhana (2020): Compared and analyzed equity fund schemes based on risk and return. The study investigated average risks/returns of selected mutual funds compared with direct equity shares, detailing their correlation.",
          "Prateek Khanna (2020): Examined the performance of mutual fund schemes ranked 1st by CRISIL and compared these returns with SBI domestic term deposit rates. The study used statistical tools such as averages and rate of returns to guide retail investors.",
          "Guruprasad Muthuseshan (2020): Attempted to understand performance and preferences from finance and marketing perspectives. Found that mutual fund awareness has risen over time and noted that advisors, agents, and relatives are key influencers of investment decisions.",
          "Muhammad Sali Maheen (2021): Studied the 'beating capacity' of actively managed funds during the COVID-19 pandemic market downturn. Using estimators like GMM on a sample of 1271 schemes, the paper concluded that actively managed Indian mutual funds co-move with the market and generally underperform or fail to beat the index in downturns.",
          "Sachin Kumar Rohatgi (2020): Looked at mutual funds as an investment vehicle for all age classes. Stressed the role of the fund manager in driving and controlling the asset allocations across capital, money, and debt markets to offer diversification.",
          "M. Blair Vorsatz (2020): Analyzed the performance and flows of U.S. actively-managed equity mutual funds during the 2020 COVID-19 crisis, finding that funds with high sustainability (ESG) and star ratings performed significantly better.",
          "Sharaz Saleem (2021): Researched investor behavior in relation to risk perception (RP), return perception, investment criteria (IC), awareness, and financial literacy, utilizing questionnaire data from 460 respondents.",
          "Ahmed K Elnagar (2020): Compared multi-cap and large-cap fund performance against diversified indices like BSE 200 and Nifty 500 from 2013 to 2018 using econometric tests such as ANOVA, concluding that both categories generated good returns.",
          "Bondu Avinash (2020): Analyzed growth-oriented equity diversified schemes before and during COVID-19 using Sharpe, Treynor, and Beta metrics based on opening and closing NAV data from AMFI.",
          "Reshma Raju (2020): Highlighted that mutual funds represent an emerging investment mode with great potential but noted that awareness in India remains relatively low.",
          "Gaurav Gupta (2021): Reviewed methods (economics and computer science) used to predict Net Asset Value (NAV) with greater accuracy to help portfolio managers optimize trade-offs.",
          "Dr. Ujjwal Mishra (2020): Evaluated the performance of select tax-saving (ELSS) mutual fund schemes in India, noting that AMCs must continuously outperform benchmarks to retain retail interest.",
          "Jasvinder Kaur (2021): Studied the performance of ethical mutual funds (Shariah index compliant) in India from 2014 to 2020, showing that 9 out of 10 ethical schemes outperformed the index with lower risk.",
          "Prem Shankar Maurya (2021): Investigated the crucial role of financial brokers and agents in encouraging retail savings during volatile periods, facilitating indirect market participation.",
          "Anirudh Sahai (2020): Traced the historical progress of Indian AMCs, investors, and schemes from 1995 to 2020, detailing the performance variance across small-cap, mid-cap, and large-cap funds."
        ]
      },
      {
        id: "ch1_3",
        title: "1.3 Importance of the Study",
        page: 21,
        content: [
          "➢ The main goal of the initiative is to present mutual funds as a superior medium for making short or long-term investments.",
          "➢ For a novice investor with limited resources, mutual funds offer a highly structured, low-risk, and useful package.",
          "➢ This project raises awareness of mutual funds as respectable investing options among the general public.",
          "➢ Mutual funds enable retail investors to make tiny, periodic investments (such as SIPs) with tailored investment objectives.",
          "➢ Mutual fund plans are run by professional asset management firms supported by banks, financial institutions, or corporations.",
          "➢ The study illustrates the rich variety of schemes (equity, debt, hybrid) that help stabilize returns in contemporary financial climates."
        ]
      },
      {
        id: "ch1_4",
        title: "1.4 Scope of the Study",
        page: 22,
        content: [
          "➢ The geographical scope of the study is centered on India Bulls Securities Limited and India Bulls Finance Company in Hyderabad, India.",
          "➢ The analysis focuses primarily on open-ended equity plans from various high-performing Asset Management Companies (AMCs) including SBI, Franklin Templeton, HDFC, Birla, Reliance, and UTI.",
          "➢ The empirical study evaluates how individual schemes perform relative to one another based on survey feedback from 50 walk-in clients."
        ]
      },
      {
        id: "ch1_5",
        title: "1.5 Objectives of the Study",
        page: 23,
        content: [
          "The core objectives of this research project include:",
          "1. To comprehend current trends and growth in the Indian mutual fund sector.",
          "2. To evaluate the perceived risk and rewards of specific mutual funds.",
          "3. To gain a clear understanding of mutual fund regulations set by SEBI.",
          "4. To assist retail investors in selecting appropriate investment plans based on statistical aspects and demographic parameters.",
          "5. To conceptualize an ideal portfolio structure using available schemes.",
          "6. To research leading mutual fund firms and the specific products they offer."
        ]
      },
      {
        id: "ch1_6",
        title: "1.6 Research Methodology",
        page: 24,
        content: [
          "Research Design: The study adopts an empirical research design to analyze investor preferences. The detailed steps are:",
          "A. Problem Formulation: The central problem was to gauge and evaluate the city population's awareness, preferences, and behavior regarding mutual fund investments.",
          "B. Developing a Research Plan:",
          "   1. Data Sources: Both primary and secondary data have been utilized. Primary data was gathered directly from respondents via surveys. Secondary data was retrieved from bank brochures, AMFI reports, financial journals, books, and online financial portals.",
          "   2. Research Instrument: A structured close-ended questionnaire was designed as the primary tool, consisting of demographic and investment preference questions.",
          "   3. Sampling Scheme:",
          "      a) Sampling Unit: Walk-in clients and retail investors in Hyderabad.",
          "      b) Sample Size: 50 active respondents selected via simple random sampling.",
          "      c) Contact Methods: In-person interviews and digital questionnaires.",
          "C. Information Gathering: Questionnaires were administered to respondents to gather factual preferences and satisfaction feedback.",
          "D. Analysis of the Data: Collected data was tabulated, analyzed with frequency distributions, and represented graphically (percentages and charts) to draw meaningful inferences."
        ]
      },
      {
        id: "ch1_7",
        title: "1.7 Chapterization",
        page: 25,
        content: [
          "The project report is organized as follows:",
          "• Chapter 1: Introduction, Review of Literature, Need, Scope, Objectives, Research Methodology, Limitations, and Chapterization.",
          "• Chapter 2: Theoretical Framework of the Study.",
          "• Chapter 3: Industry and Company Profile.",
          "• Chapter 4: Data Analysis and Interpretation (survey findings, tables, and graphs).",
          "• Chapter 5: Findings, Suggestions, and Conclusion.",
          "• Bibliography & Annexures: References, research sources, and the detailed Questionnaire."
        ]
      },
      {
        id: "ch1_8",
        title: "1.8 Limitations of the Study",
        page: 26,
        content: [
          "➢ The temporal scope of the study was limited, covering a specified study period.",
          "➢ Access was restricted only to the clients of India Bulls Finance & Securities in Hyderabad.",
          "➢ The analysis is heavily focused on open-ended equity schemes from selected AMCs.",
          "➢ Personal tax situations and individual portfolios were not modeled exhaustively.",
          "➢ High cost-to-income ratios and initial sales charges were not deeply evaluated mathematically.",
          "➢ Market volatility and macro-economic factors could skew the long-term applicability of findings."
        ]
      }
    ]
  },
  {
    id: "ch2",
    number: "2",
    title: "Theoretical Framework of Mutual Funds",
    description: "Historical evolution of mutual funds globally and in India, industry benchmarks, growth metrics, and structural advantages.",
    sections: [
      {
        id: "ch2_1",
        title: "Global Origins of Mutual Funds",
        page: 42,
        content: [
          "The concept of mutual funds was invented in Europe in the early 1770s. During a bleak economic situation, Adriaan Van Ketwich, a Dutch merchant, created the world’s first mutual fund in 1774. He pooled money from several individuals and created a diversified fund of bonds.",
          "He named it 'Eendragt Maakt Magt,' which translates to 'Unity Creates Strength.' The issue was highly successful, prompting Van Ketwich to introduce his second fund, 'Concordia Res Parvae Crescunt,' in 1779 with more freedom in investment policy. Van Ketwich’s funds survived until 1824. But the vehicle he created is still considered to be a hallmark of personal investing more than two centuries later. The early mutual fund bouquet was close-ended in nature. It spread from the Netherlands to England and France before heading to the U.S. in the 1890s."
        ]
      },
      {
        id: "ch2_2",
        title: "Evolution in the Indian Context",
        page: 42,
        content: [
          "A strong financial market with broad participation is essential for a developed economy. With this broad objective, India’s first mutual fund, the Unit Trust of India (UTI), was established in 1963 at the initiative of the Government of India and the Reserve Bank of India.",
          "The primary objective was to encourage savings and investment, and to provide retail investors a share in the profits and capital gains accruing from corporate securities. Over the years, the industry underwent massive regulatory shifts, culminating in SEBI taking control in 1993 and introducing progressive measures in September 2012 to 're-energize' the industry and expand penetration into Tier-II and Tier-III cities.",
          "These regulatory reforms successfully reversed a negative trend that had set in after the 2008 global economic melt-down. Since 2014, the industry has seen steady inflows, consistent growth in folios, and massive gains in Assets Under Management (AUM)."
        ]
      },
      {
        id: "ch2_3",
        title: "AUM Landmarks & Market Growth",
        page: 42,
        content: [
          "The Indian Mutual Fund Industry's AUM has achieved stellar milestones:",
          "• May 2014: Crossed the ₹10 Trillion (₹10 Lakh Crore) milestone for the first time.",
          "• August 2017: Doubled in size in a short span of 3 years, crossing the ₹20 Trillion (₹20 Lakh Crore) milestone.",
          "• November 2020: Crossed the ₹30 Trillion (₹30 Lakh Crore) landmark.",
          "• June 2022: Scaled to ₹35.64 Trillion, exhibiting a 5-fold increase in AUM over 10 years (from ₹6.89 Trillion in June 2012).",
          "• Investor Folios: Rose from 5.82 crore folios in June 2017 to 13.47 crore folios in June 2022. On average, 12.74 lakh new folios were added every month since June 2017.",
          "• SIP Accounts: Popularized by mutual fund distributors, the number of active Systematic Investment Plan (SIP) accounts crossed the 1 crore mark in April 2016 and expanded to a whopping 5.55 crore active accounts by June 2022."
        ]
      },
      {
        id: "ch2_4",
        title: "Core Advantages of Mutual Funds",
        page: 43,
        content: [
          "1. Professional Management: Mutual funds are operated by full-time, experienced fund managers who possess the tools, data, and resources to analyze, allocate, and rebalance portfolios to meet defined objectives.",
          "2. Risk Diversification: 'Don't put all your eggs in one basket.' Buying shares in a mutual fund distributes risk across multiple sectors, equities, bonds, or gold. If one security declines, others can offset the loss.",
          "3. Affordability & Economies of Scale: Investors can start with low amounts (as low as ₹500 via SIP). The combined pool allows the fund to trade at lower transaction costs, passing benefits to investors.",
          "4. Liquidity: Units of open-ended schemes can be easily redeemed (liquidated) on any business day. Liquid funds and overnight funds credit amounts as fast as the next business day.",
          "5. Tax Benefits: Investments in Equity Linked Savings Schemes (ELSS) qualify for tax deductions of up to ₹1,50,000 under Section 80C of the Income Tax Act, 1961, and long-term holds remain tax-efficient.",
          "6. Stringent Regulation: Governed directly by SEBI under SEBI (Mutual Funds) Regulations 1996, which lays down rules regarding transparency, valuation, expense ratio caps, and investor protection."
        ]
      }
    ]
  },
  {
    id: "ch3",
    number: "3",
    title: "Industry & Company Profile",
    description: "Overview of the Indian financial sector, historical phases, and deep dive into the corporate structure of Indiabulls.",
    sections: [
      {
        id: "ch3_1",
        title: "3.1 Indian Financial Industry Profile",
        page: 28,
        content: [
          "The Indian financial sector is in a process of rapid structural transformation aimed at boosting economic efficiency and capital allocation. The financial sector has successfully expanded products, services, and digital infrastructure to serve corporate and retail clients.",
          "History of Indian Mutual Funds is divided into four distinct phases:",
          "1. First Phase (1964-1987): Unit Trust of India (UTI) was the sole player, established in 1963. Its first scheme was Unit Scheme 1964. By 1988, UTI had ₹6,700 crores under management.",
          "2. Second Phase (1987-1993): Entry of public sector mutual funds. SBI Mutual Fund was established in June 1987, followed by Canbank, PNB, Indian Bank, BOB, and insurers LIC and GIC. AUM expanded to ₹47,004 crores by 1993.",
          "3. Third Phase (1993-2003): Entry of private sector funds. Kothari Pioneer was the first registered private fund in July 1993. SEBI (Mutual Fund) Regulations 1996 were formulated. Total AUM scaled to ₹1,21,805 crores across 33 funds.",
          "4. Fourth Phase (Since 2003): Bifurcation of UTI in February 2003 into Specified Undertaking of UTI (SUUTI) and UTI Mutual Fund (sponsored by SBI, PNB, BOB, LIC). This ushered in the current era of market consolidation, foreign fund entries, and rapid digitalization."
        ]
      },
      {
        id: "ch3_2",
        title: "3.2 Company Profile: Indiabulls Group",
        page: 34,
        content: [
          "Indiabulls Group is one of the top business houses in India, with key interests in Real Estate, Infrastructure, Financial Services, Retail, Multiplex, and Power sectors. Indiabulls Group companies are listed in Indian and overseas financial markets, and the net worth of the Group exceeds USD 2 Billion.",
          "The group's vision is to be the largest and most profitable financial services organization in the retail sector, serving as a one-stop-shop for all non-banking financial products. Indiabulls Financial Services Limited was incorporated on January 10, 2000, as Orbis Infotech, renamed in March 2001, and went public with a major IPO on February 27, 2004.",
          "Promoted by three engineers from IIT Delhi, the firm attracted over ₹700 Million in venture capital and private equity. It maintains robust corporate partnerships with major banks like Citibank, HDFC Bank, Union Bank, ICICI Bank, ABN Amro, and Standard Chartered."
        ]
      },
      {
        id: "ch3_3",
        title: "Indiabulls Securities Limited",
        page: 37,
        content: [
          "Indiabulls Securities Limited is the 'jewel in the crown' of the Indiabulls Group, providing securities trading, credit services, demat account services, mutual fund distribution, and technical market research. It operates one of the largest retail branch networks in India.",
          "Core Services Offered:",
          "• Equities & Derivatives: Purchase/sale of stocks, bonds, debentures, automated online investing, broker-assisted trades, and IPO access.",
          "• Equity Analysis: Providing fact-based rating models and portfolio building helpers, free of cost to all active clients.",
          "• Depository Services: Direct depository participant with NSDL and CDSL to enable digital settlement of dematerialized shares."
        ]
      },
      {
        id: "ch3_4",
        title: "Top Sales Structure & Helpdesk",
        page: 38,
        content: [
          "Sales Force is divided into Online & Offline groups:",
          "• EVPs Online Sales Team:",
          "  - Vijay Babbar: Managing NCR, UP, Punjab, Haryana, Uttarakhand, Rajasthan, and Gujarat.",
          "  - Amiteshwar Chaudhay: Managing Maharashtra, Goa, Kerala, Karnataka, Andhra Pradesh, and Tamil Nadu.",
          "  - Prasenjeet Mukherjee: Managing West Bengal, Orissa, Bihar, and Jharkhand.",
          "• EVPs Offline Sales Team:",
          "  - Nirdosh Gaur: NCR, Haryana, Punjab, Uttar Pradesh, Madhya Pradesh.",
          "  - Hemanshu Kamdar: Bengal, Andhra Pradesh, Tamil Nadu, Karnataka, Mumbai, Gujarat.",
          "  - Anirban Bhattacharya: Mumbai, Pune, and surrounding regions.",
          "  - Manoj Srivastava: Rajasthan, Gujarat, Mumbai.",
          "• Customer Care & Helpdesk (Gurgaon Centralized Location):",
          "  - Client Helpline: 0124 - 4572444",
          "  - Alternative Dialing: 39407777 (Local in 25 cities)",
          "  - Email support: helpdesk@indiabulls.com",
          "  - Available Cities: Ahmedabad, Bangalore, Bhopal, Chandigarh, Chennai, Coimbatore, Delhi, Hyderabad, Jaipur, Kolkata, Lucknow, Mumbai, Pune, Surat, Vadodara, Vishakhapatnam, and more."
        ]
      },
      {
        id: "ch3_5",
        title: "Milestones & Competitors",
        page: 39,
        content: [
          "Milestones Achieved by Indiabulls:",
          "• Developed one of the first internet-based trading platforms in India.",
          "• Amongst the first to integrate real-time Computer-to-Computer Link (CTCL) with NSE.",
          "• Introduced automated bank gateways for integrated user accounts.",
          "• Designed 'Power Indiabulls' trading terminal for high-volume traders.",
          "• Awarded BQ1 Highest Broker Quality Grading by CRISIL.",
          "Key Competitors in the Indian Equity Market:",
          "• ICICI Direct.com, Sharekhan (SSKI), Kotak Securities, HDFC Securities, 5paisa.com, Motilal Oswal, IL&FS, and Karvy."
        ]
      }
    ]
  },
  {
    id: "ch5",
    number: "5",
    title: "Findings, Suggestions & Conclusion",
    description: "Consolidated takeaways, tactical recommendations for mutual fund distribution, and final summary.",
    sections: [
      {
        id: "ch5_1",
        title: "5.1 Findings of the Study",
        page: 62,
        content: [
          "Based on the empirical analysis of the 50 surveyed respondents:",
          "➢ Safety is the primary consideration. 42% cite safety as their primary driver to invest with India Bulls. Bank services (20%), past experience (18%), and word of mouth (14%) follow.",
          "➢ High Client Satisfaction: 80% of respondents were extremely satisfied with India Bulls' services, 10% satisfied to a lesser extent, and only 10% experienced dissatisfaction.",
          "➢ Demographic Profile: The business class is the single largest demographic (43%), followed by students (19%), retired individuals (14%), and professionals (13%).",
          "➢ Income & Savings: 38% earn between ₹2-3 Lakhs, and 35% earn ₹1-2 Lakhs. Saving-wise, 33% save between ₹25,000-50,000 annually, while 30% save ₹50,000-1,00,000.",
          "➢ Trust in Mutual Funds: 80% believe that investing in mutual funds is a reputable and less hazardous option than direct stock market speculation.",
          "➢ Preferred Funds: Franklin Templeton is the most preferred fund house (weighted average 21.67, with 39% choosing it 1st), followed by SBI (18.62) and HDFC (18.38).",
          "➢ Portfolio Goals: 30% invest for safety, 27% for capital appreciation, 26% for tax benefits, and 17% for liquidity.",
          "➢ Investment Horizon: 63% prefer a medium-term horizon (1-3 years), 25% short-term, and 12% long-term.",
          "➢ Consultation Behavior: 35% consult financial advisors and 30% consult family members before investing, indicating a high reliance on trusted feedback loops."
        ]
      },
      {
        id: "ch5_2",
        title: "5.2 Suggestions & Recommendations",
        page: 64,
        content: [
          "➢ Elevate Salaried Class Education: Salaried individuals are highly risk-averse but possess consistent savings. AMCs should run customized seminars to educate them on mutual funds.",
          "➢ Introduce Senior and Retirement Plans: Educate and target people in their later earnings stages or retirement, highlighting safety and monthly income plans (MIPs).",
          "➢ Focus on Risk Diversification: Sales agents must clearly outline and prioritize 'risk-diversification' benefits instead of merely hyping potential high returns.",
          "➢ Bolster Tier-3 and Small Town Distribution: Expand penetration beyond metros into Tier-2 and Tier-3 cities through localized distributors.",
          "➢ Accelerate Complaint & Query Resolutions: Provide quick answers to queries to satisfy retail distributors and build brand loyalty.",
          "➢ Conduct Periodic Product Classes: Regularly hold educational events, webinars, and physical canopies to increase community connections.",
          "➢ Appoint Qualified AMFI Professionals: To build the largest and most credible distributor network, appoint professionals who have successfully cleared the AMFI exam."
        ]
      },
      {
        id: "ch5_3",
        title: "5.3 Conclusion",
        page: 65,
        content: [
          "This project successfully achieved its core objectives. Through systematic random sampling, we gained crucial insights into investor behavior and preferences in the Indian mutual fund market.",
          "Key Conclusions:",
          "• Investors show a high affinity towards mutual funds as a safer, professionally managed alternative to highly volatile direct equity markets.",
          "• Safety of the principal capital remains the ultimate driving motivation across all demographic profiles, with Franklin Templeton, SBI, and HDFC leading the market share.",
          "• India Bulls has established a high rate of client satisfaction (80% extremely satisfied) thanks to its robust customer care and diverse depository and equity services.",
          "• To unlock the next wave of retail growth, the industry must expand financial literacy, leverage digital software, and actively recruit qualified AMFI-certified advisors."
        ]
      },
      {
        id: "bib",
        title: "Bibliography & References",
        page: 67,
        content: [
          "Journals Cited:",
          "• Dr. Singh BK, 'A Study of Investors' attitude towards Mutual Funds as an Investment Option', International Journal of Research in Management, 2012.",
          "• Dr. Vyas R, 'Mutual Fund Investor's Behavior and Perception in Indore City', Journal of Arts, Science & Commerce, 2012.",
          "• Prabhavathi Y. et al, 'Investor's Preferences towards Mutual Fund and Future Investments: A Case Study of India', International Journal of Scientific and Research Publications, 2013.",
          "• Solanki A., 'A Study of Performance Evaluation of Mutual Fund and Reliance Mutual Fund', Abhinav Monthly Refereed Journal of Research in Commerce and Management, 2016.",
          "• Sindhu. K.P & Dr. S. Rajitha Kumar, 'Influence of Characteristics of Mutual Funds on Investment Decisions - A Study', International Journal of Management (IJM), 2013.",
          "• Anderson, T., & Hsiao, C. (1981), 'Estimation of dynamic models with error components', Journal of the American Statistical Association.",
          "• Arellano, M., & Bond, S. (1991), 'Some tests of specification for panel data: Monte Carlo evidence', Review of Economics Studies.",
          "Books & Websites:",
          "• David F. Swensen, (2005) 'Unconventional Success: A Fundamental Approach to Personal Investment', Free Press.",
          "• D.C. Anjaria & Dhaivat Anjaria, (2001) 'AMFI's Mutual Fund Testing Programme'.",
          "• www.google.com, www.wikipedia.org, www.indiabulls.com, www.amfiindia.com, www.moneycontrol.com"
        ]
      }
    ]
  }
];
